name: java-spring-data-jpa-plugin
description: Plugin to enable and configure Spring Data JPA in Spring Boot Java applications
display-name: java-spring-data-jpa-plugin
picture: plugin.png
category: backend # Ref: https://docs.stackspot.com/latest/docs/creators-guide/yaml/#category
compatibility:
  - java
  - spring
about: docs/about.md
usage: docs/usage.md
use-case: docs/use-case.md
implementation: docs/implementation.md
technologies: # Ref: https://docs.stackspot.com/latest/docs/creators-guide/yaml/#technologies
  - "Api"
types:
  - app
inputs:
  - label: Choose one database (RDBMS)
    name: database_name
    type: text
    items:
      - H2
      - PostgreSQL
      - MySQL

computed-inputs:
  database_name_formatted: "{{database_name|lower}}"

hooks:
  - type: edit
    path: src/main/resources/application.yaml
    trigger: after-render    
    changes:
      - search:
          string: "spring:"
          insert-after:
            snippet: snippets/snippet-datasource.jinja
          when:
            not-exists: "datasource:"
  - type: edit
    path: src/test/resources/application-test.yaml
    trigger: after-render    
    changes:
      - search:
          string: "spring:"
          insert-after:
            snippet: snippets/snippet-datasource-test.jinja
          when:
            not-exists: "datasource:"
  - type: edit
    path: pom.xml
    trigger: after-render    
    changes:
      - search:
          string: "</dependencies>"
          insert-before:
            snippet: snippets/snippet-maven-dependencies.jinja
          when:
            not-exists-snippet: snippets/snippet-maven-dependencies.jinja
      