name: java-spring-data-jpa-plugin
description: Plugin to enable and configure Spring Data JPA in Spring Boot Java applications
display-name: java-spring-data-jpa-plugin
picture: plugin.png
category: backend # Ref: https://docs.stackspot.com/latest/docs/creators-guide/yaml/#category
compatibility:
  - java
  - spring
about: docs/about.md
usage: docs/usage.md
use-case: docs/use-case.md
implementation: docs/implementation.md
technologies: # Ref: https://docs.stackspot.com/latest/docs/creators-guide/yaml/#technologies
  - "Api"
types:
  - app
inputs:
  - label: Choose one database (RDBMS)
    name: database_name
    type: text
    items:
      - H2
      - PostgreSQL
      - MySQL

computed-inputs:
  database_name_formatted: "{{database_name|lower}}"
  path_code_directory: "{{path_code_directory | replace('.','/')}}"
  path_test_code_directory: "{{path_test_code_directory | replace('.','/')}}"

hooks:
  ##
  # Edit application.yaml
  ##
  - type: edit
    path: src/main/resources/application.yaml
    trigger: after-render    
    changes:
      - search:
          string: "spring:"
          insert-after:
            snippet: snippets/snippet-application.yaml.jinja
          when:
            not-exists: "datasource:"
  ##
  # Edit application-test.yaml
  ##
  - type: edit
    path: src/test/resources/application-test.yaml
    trigger: after-render    
    changes:
      - search:
          string: "spring:"
          insert-after:
            snippet: snippets/snippet-application-test.yaml.jinja
          when:
            not-exists: "datasource:"
  ##
  # Edit pom.xml
  ##
  - type: edit
    path: pom.xml
    trigger: after-render    
    changes:
      - search:
          string: "</dependencies>"
          insert-before:
            snippet: snippets/snippet-pom.xml.jinja
          when:
            not-exists-snippet: snippets/snippet-pom.xml.jinja
  ##
  # Create or edit docker-compose.yaml
  ##
  - type: render-templates
    trigger: after-render
    path: snippets/docker-postgresql
    condition:
      variable: database_name_formatted
      operator: ==
      value: postgresql

  - type: render-templates
    trigger: after-render
    path: snippets/docker-mysql
    condition:
      variable: database_name_formatted
      operator: ==
      value: mysql
  
  ##
  # Create directory samples code
  ##

  - type: run-script
    trigger: before-input
    script: snippets/open-pom.py
    
  ##
  # Create samples code
  ##
  - type: render-templates
    trigger: after-render
    path: snippets/samples


      